"""Add new_column to GuildMember

Revision ID: 1ceeed9b9796
Revises: 
Create Date: 2024-06-30 20:44:49.943680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ceeed9b9796'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_class', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('player_spec', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('player_main_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_member', schema=None) as batch_op:
        batch_op.drop_column('player_main_id')
        batch_op.drop_column('player_spec')
        batch_op.drop_column('player_class')

    # ### end Alembic commands ###
