"""realm and region fields

Revision ID: 4f0502cb9013
Revises: 1ceeed9b9796
Create Date: 2024-07-23 19:18:00.291054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0502cb9013'
down_revision = '1ceeed9b9796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realm', sa.String(length=100), nullable=False ,server_default='Kazzak'))
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=False ,server_default='EU'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guild_member', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('region')
        batch_op.drop_column('realm')

    # ### end Alembic commands ###
